package com.livros_livres.Server.Services;

public class VariaveisHtml {

    public static String html_validarToken(String codigoVerificacao) {
        return "<!doctype html>"
    + "<html lang=\"pt-BR\">"
    + "<head>"
    + "  <meta charset=\"utf-8\"/>"
    + "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>"
    + "  <title>Validar Token - Livros Livres</title>"
    + "</head>"
    + "<body style=\"font-family:Arial, sans-serif; background:#ffffff; margin:0; padding:20px;\">"
    + "  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:600px; margin:0 auto; background:#ffd3ba; border-radius:8px; overflow:hidden; box-shadow:0 2px 6px rgb(0, 0, 0);\">"
    + "    <tr>"
    + "      <td style=\"padding:24px; text-align:center; background:#008d23; color:#ffffff;\">"
    + "        <h1 style=\"margin:0; font-size:20px; font-weight:bold;\">Livros Livres</h1>"
    + "        <p style=\"margin:6px 0 0; font-size:14px;\">Codigo de verificação - Esqueceu a senha</p>"
    + "      </td>"
    + "    </tr>"
    + "    <tr>"
    + "      <td style=\"padding:24px; color:#000000;\">"
    + "        <p>Olá, dog!</p>"
    + "        <p>Use o código abaixo para validar seu e-mail:</p>"
    + "        <p style=\"text-align:center; margin:20px 0;\">"
    + "        <p style=\"text-align:center; margin:20px 0;\">"
    + "          <span style=\"display:inline-block; padding:12px 18px; font-size:18px; letter-spacing:2px; border-radius:6px; background:#f1f5f9; color:#000000\">"
    +              codigoVerificacao
    + "          </span>"
    + "        </p>"
    + "        <p>Livros Livres</p>"
    + "      </td>"
    + "    </tr>"
    + "    <tr>"
    + "      <td style=\"padding:14px; text-align:center; font-size:12px; color:#999999; background:#fafafa;\">"
    + "        &copy; " + java.time.Year.now().getValue() + " Livros Livres. Todos os direitos reservados."
    + "      </td>"
    + "    </tr>"
    + "  </table>"
    + "</body>"
    + "</html>";
    }


    public static String html_esqueciSenha(String codigoVerificacao) {
    return "<!doctype html>"
    + "<html lang=\"pt-BR\">"
    + "<head>"
    + "  <meta charset=\"utf-8\"/>"
    + "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>"
    + "  <title>Validar Token - Livros Livres</title>"
    + "</head>"
    + "<body style=\"font-family:Arial, sans-serif; background:#ffffff; margin:0; padding:20px;\">"
    + "  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:600px; margin:0 auto; background:#ffd3ba; border-radius:8px; overflow:hidden; box-shadow:0 2px 6px rgb(0, 0, 0);\">"
    + "    <tr>"
    + "      <td style=\"padding:24px; text-align:center; background:#008d23; color:#ffffff;\">"
    + "        <h1 style=\"margin:0; font-size:20px; font-weight:bold;\">Livros Livres</h1>"
    + "        <p style=\"margin:6px 0 0; font-size:14px;\">Codigo de verificação - Esqueceu a senha</p>"
    + "      </td>"
    + "    </tr>"
    + "    <tr>"
    + "      <td style=\"padding:24px; color:#000000;\">"
    + "        <p>Olá, dog!</p>"
    + "        <p>Use o código abaixo para efetuar a troca de sua senha:</p>"
    + "        <p style=\"text-align:center; margin:20px 0;\">"
    + "        <p style=\"text-align:center; margin:20px 0;\">"
    + "          <span style=\"display:inline-block; padding:12px 18px; font-size:18px; letter-spacing:2px; border-radius:6px; background:#f1f5f9; color:#000000\">"
    +              codigoVerificacao
    + "          </span>"
    + "        </p>"
    + "        <p>Livros Livres</p>"
    + "      </td>"
    + "    </tr>"
    + "    <tr>"
    + "      <td style=\"padding:14px; text-align:center; font-size:12px; color:#999999; background:#fafafa;\">"
    + "        &copy; " + java.time.Year.now().getValue() + " Livros Livres. Todos os direitos reservados."
    + "      </td>"
    + "    </tr>"
    + "  </table>"
    + "</body>"
    + "</html>";
    }

    public static String html_clienteCriadoFunc(String codigoVerificacao, String email){
       
        return "<!doctype html>"
    + "<html lang=\"pt-BR\">"
    + "<head>"
    + "  <meta charset=\"utf-8\"/>"
    + "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>"
    + "  <title>Validar Token - Livros Livres</title>"
    + "</head>"
    + "<body style=\"font-family:Arial, sans-serif; background:#ffffff; margin:0; padding:20px;\">"
    + "  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:600px; margin:0 auto; background:#ffd3ba; border-radius:8px; overflow:hidden; box-shadow:0 2px 6px rgb(0, 0, 0);\">"
    + "    <tr>"
    + "      <td style=\"padding:24px; text-align:center; background:#008d23; color:#ffffff;\">"
    + "        <h1 style=\"margin:0; font-size:20px; font-weight:bold;\">Livros Livres</h1>"
    + "        <p style=\"margin:6px 0 0; font-size:14px;\">Codigo de verificação - Esqueceu a senha</p>"
    + "      </td>"
    + "    </tr>"
    + "    <tr>"
    + "      <td style=\"padding:24px; color:#000000;\">"
    + "        <p>Olá, dog!</p>"
    + "        <p>Sua conta do livros livres foi criada por um de nossos funcionários!</p>"
    + "        <p>Segue seu acesso para acessar sua conta por este link: "
    + "          http://127.0.0.1:5500/public/html/pages/login/login-forgotpwd.html?email=" + email
    + "        </p>"
    + "        <p>Use o código para efetuar a troca de sua senha:</p>"
    + "        <p style=\"text-align:center; margin:20px 0;\">"
    + "          <span style=\"display:inline-block; padding:12px 18px; font-size:18px; letter-spacing:2px; border-radius:6px; background:#f1f5f9; color:#000000\">"
    +              codigoVerificacao
    + "          </span>"
    + "        </p>"
    + "        <p>Livros Livres</p>"
    + "      </td>"
    + "    </tr>"
    + "    <tr>"
    + "      <td style=\"padding:14px; text-align:center; font-size:12px; color:#999999; background:#fafafa;\">"
    + "        &copy; " + java.time.Year.now().getValue() + " Livros Livres. Todos os direitos reservados."
    + "      </td>"
    + "    </tr>"
    + "  </table>"
    + "</body>"
    + "</html>";
    }
}
